# initial_mean_degree : [0.0, 0.0, 20.0] # banana
# initial_mean_degree : [-70, 180, 0] # banana center


initial_mean_degree : [
  0.0, 0.0, 0.0,
  0.0, 0.0, 0.0,
  0.045,
] # banana
# -------
initial_std_dev: 1 # 10 # 0.01 # 3.0
# -------
n_jobs         : 8
