# mode         : 0 # plot
mode         : 1 # save
# ----
axis_label  : True # False
empty_ticks :  True
use_title   : True # False
# ----
# figsize       : [13, 13] # [6, 6]
figsize       : [8, 8]
# figsize       : [4, 4]
# save_path     : "./ipfo.pdf"
elev         : 45
azim         : 45
# point_size   : 2 #"5 # 10
# normal_length: 0.005 # 0.0025
# point_alpha  : 1.0
# normal_alpha : 1.0
label_fontsize : 14
# ----
hand_origin_point_size    : 15
hand_origin_normal_length : 0.01

# ------
use_fixed_limit: True
# ---
x_min : -0.04 # 0.1
x_max :  0.04 # 0.1
# ---
y_min : -0.04 # 0.1
y_max :  0.04 # 0.1
# ---
z_min : -0.04 # 0.1
z_max :  0.04 # 0.1




# -------
point_normal:
  # ----------------
  #      point
  # ----------------
  point_size:
    target:
      surface: 5
      contact: 5
      correspondence : 5
    source:
      contact: 5
      correspondence: 5
  # ----------------
  point_alpha:
    target:
      surface: 0.3
      contact: 1.0
      correspondence: 1.0
    source:
      contact: 1.0
      correspondence: 1.0
  # ----------------
  #      normal
  # ----------------
  normal_length:
    target:
      surface: 0
      contact: 0
      # correspondence: 0.012
      correspondence: 0.005 # box
    source:
      contact: 0
      # correspondence: 0.012
      correspondence: 0.005 # box
    n_z  : 0.05
    n_app: 0.05
  # ----------------
  normal_alpha:
    target:
      surface: 1
      contact: 1
      correspondence: 1
    source:
      contact: 1
      correspondence: 1
    n_z  : 1.0
    n_app: 1.0

  # ----------------
  #      color
  # ----------------
  color:
    target:
      surface: 1.0
      contact: 1.0
      correspondence: "blue"
    source:
      contact_skew: {
          "1" : "tan",      # right
          "2" : "lightblue", # left
      }
      contact: {
        "1" : "plum",      # right
        "2" : "limegreen", # left
      }
      correspondence: {
        "1" : "red",   # right
        "2" : "green", # left
      }
      correspondence_skew: {
        "1" : "darkgoldenrod",   # right
        "2" : "teal", # left
      }

    n_z  : "darkorange"
    n_app: "purple"

  # ----------------
  #    linestyles
  # ----------------
  linestyles:
    n_z: "-"
    n_app: "-"
