defaults:
  - _self_
  - load          : default
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "000_box"
# ----
n_approach: [1, 0, 0]
# ----
gripper_pose:
  translation        : [0, 0, 0]
  # euler_angle_degree : [1, 90, 0]
  # euler_angle_degree : [1, 0, 0]
  euler_angle_degree : [0, 0, 1]
# ----
contact_plane:
  # ----
  position_origin   : [0, 0, 0.04]
  normal_direction_z: [0, 0, -1]
  # ----
  d1 : # 手平面からの許容距離
  d2 : # 手平面原点からの許容距離

# ///// special param /////
# object_half_size: 0.001
# object_half_size: 0.003
object_half_size: 0.005
# object_half_size: 0.010
