defaults:
  - _self_
  - load          : default
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "006_mustard_bottle"
# ----
n_approach: [1, -1, 0]  # robot [-0.5, 0, 0]
# ----
gripper_pose:
  translation       : [0, 0, 0]
  # euler_angle_degree: [0, 90, -50]
  euler_angle_degree: [0, 45, -50]
# ----
contact_plane:
  # ----
  position_origin   : [-0.03, 0, 0]
  normal_direction_z: [-1, 1.3, 0]
  # ----
  d1 : 0.018   # 手平面からの許容距離
  d2 : 0.15    # 手平面原点からの許容距離
