defaults:
  - _self_
  - load          : default
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "029_plate"
# ----
n_approach: [0, -1, 0] # side
# n_approach: [1, 1, 0] # side
# n_approach: [1, 0, 0] # center from foreground
# ----
gripper_pose:
  translation        : [0, 0, 0]
  euler_angle_degree : [80, 0, 45]
  # euler_angle_degree : [90, 0, 90]
# ----
contact_plane:
  # ---- side -----
  position_origin   : [-0.05, 0.5, 0]
  normal_direction_z: [1, 0, 0]
  # ---- center from foreground ----
  # position_origin   : [-0.5, 0, 0]
  # normal_direction_z: [0, -1, 0]
  # ----
  d1 : 0.018   # 手平面からの許容距離
  d2 : 0.4    # 手平面原点からの許容距離
