defaults:
  - _self_
  - load          : default
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "042_adjustable_wrench"
# ----
n_approach: [1, -1, 0]
# ----
gripper_pose:
  translation        : [0, 0, 0]
  euler_angle_degree : [70, 0, 0]
# ----
contact_plane:
  # ----
  position_origin   : [-0.12, 0, 0]
  normal_direction_z: [0, 1, 0]
  # ----
  d1 : 0.018   # 手平面からの許容距離
  d2 : 0.15    # 手平面原点からの許容距離
