defaults:
  - _self_
  - load          : default
  - pre_prosessing: default
  - generate      : default
# ------------------------------------------
model_name: "065-j_cups"
# ----
n_approach: [0, 0, -1]
# ----
gripper_pose:
  translation        : [0, 0, 0]
  euler_angle_degree : [-180, 60, 0]
# ----
contact_plane:
  # ----
  position_origin   : [0, 0.13, 0.1]
  normal_direction_z: [1, 0, 0]
  # ----
  d1 : 0.018   # 手平面からの許容距離
  d2 : 0.15    # 手平面原点からの許容距離
